# Generated by Django 5.2.11 on 2026-03-03 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_sweatshirt_size_remove_t_shirt_size'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 't_shirt', 'sweatshirt', 'size')},
        ),
    ]
