# Generated by Django 5.2.11 on 2026-02-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisabilityVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_and_surname', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('remote', 'Remote'), ('internship', 'Internship'), ('flexible', 'Flexible schedule')], max_length=250)),
                ('category', models.CharField(choices=[('visual', 'Visual impairment'), ('hearing', 'Hearing impairment'), ('musculoskeletal', 'Musculoskeletal disorders'), ('mental', 'Mental health conditions'), ('speech', 'Speech impairment'), ('other', 'Other disabilities')], max_length=250)),
                ('level', models.CharField(choices=[('none', 'No education'), ('secondary', 'Secondary education'), ('vocational', 'Vocational education'), ('higher', 'Higher education'), ('academic', 'Academic degree')], max_length=250)),
                ('text', models.TextField(blank=True, null=True, verbose_name='Additionally, I would like to specify:')),
                ('resume_file', models.FileField(upload_to='resumes/', verbose_name='Резюме')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
        ),
    ]
