# Generated by Django 5.2.11 on 2026-03-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_and_surname', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('remote', 'Remote'), ('internship', 'Internship'), ('flexible', 'Flexible schedule')], max_length=250)),
                ('level', models.CharField(choices=[('none', 'No education'), ('secondary', 'Secondary education'), ('vocational', 'Vocational education'), ('higher', 'Higher education'), ('academic', 'Academic degree')], max_length=250)),
                ('phone_number', models.CharField(default='')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('text', models.TextField(blank=True, null=True, verbose_name='Additionally, I would like to specify:')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='Резюме')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
        ),
        migrations.CreateModel(
            name='YoungVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_and_surname', models.CharField(max_length=200)),
                ('years', models.IntegerField()),
                ('text', models.TextField(blank=True, null=True, verbose_name='Additionally, I would like to specify:')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='Резюме')),
                ('phone_number', models.CharField()),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
        ),
        migrations.AddField(
            model_name='disabilityvacancy',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='disabilityvacancy',
            name='phone_number',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='disabilityvacancy',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='Резюме'),
        ),
    ]
