# Generated by Django 5.2.10 on 2026-03-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_vacancy_youngvacancy_disabilityvacancy_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cooperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_and_surname', models.CharField(max_length=200)),
                ('phone_number', models.CharField()),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('text', models.TextField(blank=True, null=True, verbose_name='Additionally, I would like to specify:')),
                ('document', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='Документ')),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_and_surname', models.CharField(max_length=200)),
                ('phone_number', models.CharField()),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('money', models.IntegerField()),
                ('text', models.TextField(blank=True, null=True, verbose_name='Additionally, I would like to specify:')),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_and_surname', models.CharField(max_length=200)),
                ('phone_number', models.CharField()),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='Документ')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Additionally, I would like to specify:')),
            ],
        ),
    ]
