# Generated by Django 5.2.10 on 2026-02-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='type',
            field=models.CharField(choices=[('CA', 'CA'), ('USA', 'USA')], default='CA'),
        ),
    ]
