# Generated by Django 5.2.10 on 2026-02-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_shop_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
    ]
