# Generated by Django 5.2.10 on 2026-02-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
