# Generated by Django 5.2.11 on 2026-03-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='type',
            field=models.CharField(choices=[('CA', 'CA'), ('USA', 'USA')], default='CA', max_length=3),
        ),
        migrations.AlterField(
            model_name='office',
            name='type',
            field=models.CharField(choices=[('CA', 'CA'), ('USA', 'USA')], default='CA', max_length=3),
        ),
        migrations.AlterField(
            model_name='shop',
            name='type',
            field=models.CharField(choices=[('CA', 'CA'), ('USA', 'USA')], default='CA', max_length=3),
        ),
        migrations.AlterField(
            model_name='support',
            name='type',
            field=models.CharField(choices=[('USA', 'USA'), ('CA', 'CA')], default='CA', max_length=3),
        ),
    ]
