# Generated by Django 5.2.10 on 2026-02-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('Order and delivery', 'Order and delivery'), ('Product', 'Product'), ('Website', 'Website'), ('Refund and exchange', 'Refund and exchange'), ('Other', 'Other')], default='Other', max_length=50)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
