# Generated by Django 5.2.11 on 2026-03-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sweatshirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image2', models.URLField(max_length=250)),
                ('name', models.CharField(max_length=100)),
                ('structure', models.CharField(default='cotton', max_length=100)),
                ('price', models.CharField(max_length=20)),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='M')),
                ('text', models.TextField(verbose_name='about')),
            ],
        ),
        migrations.CreateModel(
            name='T_shirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image2', models.URLField(max_length=250)),
                ('name', models.CharField(max_length=100)),
                ('structure', models.CharField(default='cotton', max_length=100)),
                ('price', models.CharField(max_length=20)),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='M')),
                ('text', models.TextField(verbose_name='about')),
            ],
        ),
    ]
