# Generated by Django 5.2.11 on 2026-03-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_sweatshirt_t_shirt'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialcollections',
            name='color',
            field=models.CharField(default='black', max_length=200),
        ),
        migrations.AddField(
            model_name='sweatshirt',
            name='image',
            field=models.ImageField(default='null', upload_to=''),
        ),
        migrations.AddField(
            model_name='t_shirt',
            name='image',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
