# Generated by Django 5.2.11 on 2026-03-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_specialcollections_color_sweatshirt_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweatshirt',
            name='image',
            field=models.ImageField(blank=True, default='null', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sweatshirt',
            name='image2',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_shirt',
            name='image',
            field=models.ImageField(blank=True, default='null', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='t_shirt',
            name='image2',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
