# Generated by Django 5.2.11 on 2026-03-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_sweatshirt_image_alter_sweatshirt_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweatshirt',
            name='collections_type',
            field=models.CharField(choices=[('Modern Minimalism', 'Modern Minimalism'), ('The promise of hope', 'The promise of hope'), ('The Crying Machiavelli', 'The Crying Machiavelli'), ('Blood money', 'Blood money')], default='Modern Minimalism'),
        ),
        migrations.AddField(
            model_name='t_shirt',
            name='collections_type',
            field=models.CharField(choices=[('Modern Minimalism', 'Modern Minimalism'), ('The promise of hope', 'The promise of hope'), ('The Crying Machiavelli', 'The Crying Machiavelli'), ('Blood money', 'Blood money')], default='Modern Minimalism'),
        ),
    ]
