# Generated by Django 5.2.11 on 2026-03-03 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_sweatshirt_collections_type_t_shirt_collections_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sweatshirt',
            name='size',
        ),
        migrations.RemoveField(
            model_name='t_shirt',
            name='size',
        ),
    ]
