# Generated by Django 5.2.11 on 2026-03-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_sweatshirt_size_remove_t_shirt_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweatshirt',
            name='collections_type',
            field=models.CharField(choices=[('Modern Minimalism', 'Modern Minimalism'), ('The promise of hope', 'The promise of hope'), ('The Crying Machiavelli', 'The Crying Machiavelli'), ('Blood money', 'Blood money'), ('The March Collection', 'The March Collection')], default='Modern Minimalism'),
        ),
        migrations.AlterField(
            model_name='t_shirt',
            name='collections_type',
            field=models.CharField(choices=[('Modern Minimalism', 'Modern Minimalism'), ('The promise of hope', 'The promise of hope'), ('The Crying Machiavelli', 'The Crying Machiavelli'), ('Blood money', 'Blood money'), ('The March Collection', 'The March Collection'), ('The weihgt of Shadow & Rick and Morty', 'The weihgt of Shadow & Rick and Morty')], default='Modern Minimalism'),
        ),
    ]
